README.md

Please provide any testing evidence to show that your Pull Request works/fixes as described and planned (include screenshots, if appropriate).

Update readme for v0.0.1

---

.github/workflows/go-test-deployment.yml
.github/workflows/go-test-unit.yml

Please provide any testing evidence to show that your Pull Request works/fixes as described and planned (include screenshots, if appropriate).

Fix workflows

---

.github/fabricbot.json
.github/workflows/go-test-deployment.yml

1. fixes logic in condition for deployment job
2. prevents fabricbot from spamming the replies ;-)

deployment test update condition

---

.github/workflows/housekeep-deleteresourcegroups.yml

Please provide any testing evidence to show that your Pull Request works/fixes as described and planned (include screenshots, if appropriate).

fix workflow name

---

.github/fabricbot.json
main.virtualnetwork.tf
modules/virtualnetwork/locals.tf

Fixes virtual network submodule location coalesce incorrect #37

---

.github/workflows/housekeep-cancelsubscriptions.yml
.github/workflows/housekeep-deleteresourcegroups.yml
.github/workflows/housekeep-deletesubscriptionaliases.yml

Housekeepingfix

---

.github/workflows/go-test-deployment.yml
.github/workflows/go-test-unit.yml

correct workflows

---

CONTRIBUTING.md
DEVELOPER.md
README.md
locals.tf
main.roleassignment.tf
modules/roleassignment/testdata/TestDeployRoleAssignmentDefinitionId/main.tf
modules/roleassignment/testdata/TestDeployRoleAssignmentDefinitionId/variables.tf
modules/roleassignment/testdata/TestDeployRoleAssignmentDefinitionName/main.tf
modules/roleassignment/testdata/TestDeployRoleAssignmentDefinitionName/variables.tf
terraform.tf
tests/integration/integration_test.go
tests/roleassignment/roleassignmentDeploy_test.go
tests/roleassignment/roleassignment_test.go
tests/subscription/subscription_test.go
tests/virtualnetwork/virtualnetwork_test.go

1. Fixes #51 
2. Comment tidy
3. Role assignments now depends on other modules

Add role assignment deployment tests

---

.github/workflows/wiki-sync.yml

1. Fixes issue where wiki sync will fail if no changes

Wiki sync - Exit if no changes

---

.github/workflows/pr-lint.yml

fix: pr lint workflow

---

docs/wiki/Upgrades.md

docs: add documentation for version upgrades

---

README.md
docs/wiki/_Sidebar.md
header.md
modules/roleassignment/README.md
modules/roleassignment/header.md
modules/subscription/README.md
modules/subscription/header.md
modules/virtualnetwork/README.md
modules/virtualnetwork/header.md

1. Fixes submodule README links to parent module
2. Adds parent module link to change log
3. Update wiki sidebar

docs: fix links & add changelog section

---

README.md
header.md

docs: correct README

---

.github/workflows/super-linter.yml

1. disables terrascan as not compatible with TF 1.3 optional

fix: disable terrascan

---

README.md
header.md
locals.version.tf.json
variables.virtualnetwork.tf

1. Minor fixes to fix display issues on registry

docs: fix issues with display on Terraform registry

---

README.md
locals.version.tf.json
modules/virtualnetwork/README.md
modules/virtualnetwork/variables.tf
variables.virtualnetwork.tf

1. fixes #121
2. updated module version to 2.0.2

fix: virtual_networks value type & README

---

locals.version.tf.json

chore: update version to 2.1.0

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md
SUPPORT.md
docs/wiki/Example-4-Integration-with-ALZ-module.md
docs/wiki/Permissions.md

1. updates permissions required
2. adds circular dependency section to integration with ALZ module
3. Updates bug report & feature request issue templates
4. Minor updates to PR template

docs: wiki updates

---

README.md
header.md

1. Adds Is It Maintained? badge to README

docs: add badges

---

.github/workflows/go-test-deployment.yml
.github/workflows/go-test-unit.yml
tests/integration/integrationDeploy_test.go
tests/integration/integration_test.go
tests/roleassignment/roleassignmentDeploy_test.go
tests/roleassignment/roleassignment_test.go
tests/subscription/subscriptionDeploy_test.go
tests/subscription/subscription_test.go
tests/virtualnetwork/virtualnetworkDeploy_test.go
tests/virtualnetwork/virtualnetwork_test.go

1. Introduces parallel tests, reducing execution time by 8-10x depending on number of cores.
Testing evidence
See test run evidence

test: parallel tests

---

docs/wiki/Example-4-Integration-with-ALZ-module.md

Updates wiki page with mermaid diagram
1. fixes #142

docs: update ALZ wiki page

---

.github/fabricbot.json

1. Fabricbot new action - Remove needs attention label when needs author feedback label added

feat: add fabricbot label action

---

docs/wiki/Upgrades.md

1. adds note to upgrade guide explaining impact of v2 -> v3 upgrade.

docs: add text on role assignment re-creation

---

.github/workflows/super-linter.yml

feat: golangci-lint 1.52.2

---

.github/workflows/go-test-deployment.yml
.github/workflows/go-test-unit.yml

chore: raise azapi matrix version to 1.3.0

---

.github/workflows/housekeep.yml

Adds remove locks
1. fixes #000

fix: housekeep

---

variables.resourcegroup.tf
variables.resourceprovider.tf
variables.roleassignment.tf
variables.subscription.tf
variables.usermanagedidentity.tf
variables.virtualnetwork.tf

This PR adds [nullable = false](https://developer.hashicorp.com/terraform/language/values/variables#disallowing-null-input-values) to some variables where some type is expected and a default value is given to allow setting `null` to fall back to its variable default.
1. fixes #267 

fix(): added `nullable = false` to fix Error: Iteration over null value

---

.github/workflows/super-linter.yml

chore: update lint ci

---

locals.tf

fix: #290 virtual network ourputs

---

.tfdocs-config.yml
Makefile

feat: tfdocs 0.17.0

---

modules/resourcegroup/README.md
modules/resourceprovider/README.md
modules/roleassignment/README.md
modules/subscription/README.md
modules/usermanagedidentity/README.md
modules/virtualnetwork/README.md

chore: make docs

---

.github/workflows/go-test-unit.yml

ci: update azapi and terraform minimums

---

README.md
header.md

There is a legacy variable name in the primary example in the docs. 
N/A
Docs only
Docs only

docs: fix typo in docs

---

modules/subscription/variables.tf
tests/subscription/subscription_test.go

Adds validation for subscription tags
1. fixes #332

fix: add validation for subscription tags

---

modules/subscription/variables.tf
tests/subscription/subscription_test.go

fix(subscription): validation rule for tag values

---

locals.version.tf.json

fix: update telemetry version 

---

.github/workflows/scorecard.yml
README.md
header.md

Add OpenSFF scoredcard and badge
N/A
N/A
N/A

chore: add openssf scorecard

---

README.md
header.md
modules/subscription/variables.tf
variables.resourceprovider.tf

1. fixes #461
2. fixes #451
3. fixes #444

fix: invalid provider in rp reg & subscription validation rules
